package com.ipn.mx.siipg.modelo;
// Generated 12/12/2016 01:27:14 AM by Hibernate Tools 4.3.1



/**
 * Opcionesmenu generated by hbm2java
 */
public class Opcionesmenu  implements java.io.Serializable {


     private Integer id;
     private Menu menu;
     private String nombre;
     private String ruta;

    public Opcionesmenu() {
    }

    public Opcionesmenu(Menu menu, String nombre, String ruta) {
       this.menu = menu;
       this.nombre = nombre;
       this.ruta = ruta;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Menu getMenu() {
        return this.menu;
    }
    
    public void setMenu(Menu menu) {
        this.menu = menu;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getRuta() {
        return this.ruta;
    }
    
    public void setRuta(String ruta) {
        this.ruta = ruta;
    }




}


