package com.ipn.mx.siipg.modelo;
// Generated 12/12/2016 01:27:14 AM by Hibernate Tools 4.3.1



/**
 * UsuarioId generated by hbm2java
 */
public class UsuarioId  implements java.io.Serializable {


     private int id;
     private String rfc;

    public UsuarioId() {
    }

    public UsuarioId(int id, String rfc) {
       this.id = id;
       this.rfc = rfc;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getRfc() {
        return this.rfc;
    }
    
    public void setRfc(String rfc) {
        this.rfc = rfc;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsuarioId) ) return false;
		 UsuarioId castOther = ( UsuarioId ) other; 
         
		 return (this.getId()==castOther.getId())
 && ( (this.getRfc()==castOther.getRfc()) || ( this.getRfc()!=null && castOther.getRfc()!=null && this.getRfc().equals(castOther.getRfc()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + ( getRfc() == null ? 0 : this.getRfc().hashCode() );
         return result;
   }   


}


