package com.ipn.mx.siipg.modelo;
// Generated 12/12/2016 01:27:14 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Entidadfederativa generated by hbm2java
 */
public class Entidadfederativa  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set unidadresponsables = new HashSet(0);

    public Entidadfederativa() {
    }

	
    public Entidadfederativa(String nombre) {
        this.nombre = nombre;
    }
    public Entidadfederativa(String nombre, Set unidadresponsables) {
       this.nombre = nombre;
       this.unidadresponsables = unidadresponsables;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getUnidadresponsables() {
        return this.unidadresponsables;
    }
    
    public void setUnidadresponsables(Set unidadresponsables) {
        this.unidadresponsables = unidadresponsables;
    }




}


