package com.ipn.mx.siipg.modelo;
// Generated 12/12/2016 01:27:14 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Indicador generated by hbm2java
 */
public class Indicador  implements java.io.Serializable {


     private Integer id;
     private Ejetematico ejetematico;
     private String nombre;
     private String agendaVinculada;
     private String descripcion;
     private String cobertura;
     private byte[] metodologia;
     private Float resultado;
     private Set variablechecks = new HashSet(0);

    public Indicador() {
    }

	
    public Indicador(Ejetematico ejetematico, String nombre, String descripcion, String cobertura, byte[] metodologia) {
        this.ejetematico = ejetematico;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.cobertura = cobertura;
        this.metodologia = metodologia;
    }
    public Indicador(Ejetematico ejetematico, String nombre, String agendaVinculada, String descripcion, String cobertura, byte[] metodologia, Float resultado, Set variablechecks) {
       this.ejetematico = ejetematico;
       this.nombre = nombre;
       this.agendaVinculada = agendaVinculada;
       this.descripcion = descripcion;
       this.cobertura = cobertura;
       this.metodologia = metodologia;
       this.resultado = resultado;
       this.variablechecks = variablechecks;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Ejetematico getEjetematico() {
        return this.ejetematico;
    }
    
    public void setEjetematico(Ejetematico ejetematico) {
        this.ejetematico = ejetematico;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getAgendaVinculada() {
        return this.agendaVinculada;
    }
    
    public void setAgendaVinculada(String agendaVinculada) {
        this.agendaVinculada = agendaVinculada;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getCobertura() {
        return this.cobertura;
    }
    
    public void setCobertura(String cobertura) {
        this.cobertura = cobertura;
    }
    public byte[] getMetodologia() {
        return this.metodologia;
    }
    
    public void setMetodologia(byte[] metodologia) {
        this.metodologia = metodologia;
    }
    public Float getResultado() {
        return this.resultado;
    }
    
    public void setResultado(Float resultado) {
        this.resultado = resultado;
    }
    public Set getVariablechecks() {
        return this.variablechecks;
    }
    
    public void setVariablechecks(Set variablechecks) {
        this.variablechecks = variablechecks;
    }




}


