package com.ipn.mx.siipg.modelo;
// Generated 12/12/2016 01:27:14 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol  implements java.io.Serializable {


     private Integer id;
     private String rol;
     private Set usuarios = new HashSet(0);
     private Set menus = new HashSet(0);

    public Rol() {
    }

	
    public Rol(String rol) {
        this.rol = rol;
    }
    public Rol(String rol, Set usuarios, Set menus) {
       this.rol = rol;
       this.usuarios = usuarios;
       this.menus = menus;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getRol() {
        return this.rol;
    }
    
    public void setRol(String rol) {
        this.rol = rol;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }
    public Set getMenus() {
        return this.menus;
    }
    
    public void setMenus(Set menus) {
        this.menus = menus;
    }




}


