package com.ipn.mx.siipg.modelo;
// Generated 12/12/2016 01:27:14 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Unidadresponsable generated by hbm2java
 */
public class Unidadresponsable  implements java.io.Serializable {


     private Integer id;
     private Areapolitecnica areapolitecnica;
     private Entidadfederativa entidadfederativa;
     private int estatus;
     private String nombre;
     private String direccion;
     private Set variables = new HashSet(0);
     private Set usuarios = new HashSet(0);

    public Unidadresponsable() {
    }

	
    public Unidadresponsable(Areapolitecnica areapolitecnica, Entidadfederativa entidadfederativa, int estatus, String nombre) {
        this.areapolitecnica = areapolitecnica;
        this.entidadfederativa = entidadfederativa;
        this.estatus = estatus;
        this.nombre = nombre;
    }
    public Unidadresponsable(Areapolitecnica areapolitecnica, Entidadfederativa entidadfederativa, int estatus, String nombre, String direccion, Set variables, Set usuarios) {
       this.areapolitecnica = areapolitecnica;
       this.entidadfederativa = entidadfederativa;
       this.estatus = estatus;
       this.nombre = nombre;
       this.direccion = direccion;
       this.variables = variables;
       this.usuarios = usuarios;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Areapolitecnica getAreapolitecnica() {
        return this.areapolitecnica;
    }
    
    public void setAreapolitecnica(Areapolitecnica areapolitecnica) {
        this.areapolitecnica = areapolitecnica;
    }
    public Entidadfederativa getEntidadfederativa() {
        return this.entidadfederativa;
    }
    
    public void setEntidadfederativa(Entidadfederativa entidadfederativa) {
        this.entidadfederativa = entidadfederativa;
    }
    public int getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(int estatus) {
        this.estatus = estatus;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Set getVariables() {
        return this.variables;
    }
    
    public void setVariables(Set variables) {
        this.variables = variables;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


