package com.ipn.mx.siipg.modelo;
// Generated 27/11/2016 04:37:03 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Unidadacademica generated by hbm2java
 */
public class Unidadacademica  implements java.io.Serializable {


     private Integer id;
     private int estatus;
     private Date createdAt;
     private Date updatedAt;
     private String nombre;
     private String direccion;
     private String entidadFederativa;
     private Set usuarios = new HashSet(0);

    public Unidadacademica() {
    }

	
    public Unidadacademica(int estatus, String nombre) {
        this.estatus = estatus;
        this.nombre = nombre;
    }
    public Unidadacademica(int estatus, Date createdAt, Date updatedAt, String nombre, String direccion, String entidadFederativa, Set usuarios) {
       this.estatus = estatus;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.nombre = nombre;
       this.direccion = direccion;
       this.entidadFederativa = entidadFederativa;
       this.usuarios = usuarios;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(int estatus) {
        this.estatus = estatus;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getEntidadFederativa() {
        return this.entidadFederativa;
    }
    
    public void setEntidadFederativa(String entidadFederativa) {
        this.entidadFederativa = entidadFederativa;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


