package com.ipn.mx.siipg.modelo;
// Generated 27/11/2016 04:37:03 AM by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer id;
     private Rol rol;
     private Unidadacademica unidadacademica;
     private String rfc;
     private String password;
     private int status;
     private String createdAt;
     private String updatedAt;
     private String nombre;
     private String apellidoPaterno;
     private String apellidoMaterno;
     private String numeroEmpleado;
     private String email;
     private String telefonos;

    public Usuario() {
    }

	
    public Usuario(Rol rol, Unidadacademica unidadacademica, String rfc, String password, int status, String numeroEmpleado) {
        this.rol = rol;
        this.unidadacademica = unidadacademica;
        this.rfc = rfc;
        this.password = password;
        this.status = status;
        this.numeroEmpleado = numeroEmpleado;
    }
    public Usuario(Rol rol, Unidadacademica unidadacademica, String rfc, String password, int status, String createdAt, String updatedAt, String nombre, String apellidoPaterno, String apellidoMaterno, String numeroEmpleado, String email, String telefonos) {
       this.rol = rol;
       this.unidadacademica = unidadacademica;
       this.rfc = rfc;
       this.password = password;
       this.status = status;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.nombre = nombre;
       this.apellidoPaterno = apellidoPaterno;
       this.apellidoMaterno = apellidoMaterno;
       this.numeroEmpleado = numeroEmpleado;
       this.email = email;
       this.telefonos = telefonos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public Unidadacademica getUnidadacademica() {
        return this.unidadacademica;
    }
    
    public void setUnidadacademica(Unidadacademica unidadacademica) {
        this.unidadacademica = unidadacademica;
    }
    public String getRfc() {
        return this.rfc;
    }
    
    public void setRfc(String rfc) {
        this.rfc = rfc;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    public String getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }
    public String getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(String updatedAt) {
        this.updatedAt = updatedAt;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidoPaterno() {
        return this.apellidoPaterno;
    }
    
    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }
    public String getApellidoMaterno() {
        return this.apellidoMaterno;
    }
    
    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }
    public String getNumeroEmpleado() {
        return this.numeroEmpleado;
    }
    
    public void setNumeroEmpleado(String numeroEmpleado) {
        this.numeroEmpleado = numeroEmpleado;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTelefonos() {
        return this.telefonos;
    }
    
    public void setTelefonos(String telefonos) {
        this.telefonos = telefonos;
    }




}


