package com.ipn.mx.siipg.modelo;
// Generated 12/12/2016 01:27:14 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Variable generated by hbm2java
 */
public class Variable  implements java.io.Serializable {


     private int id;
     private Unidadresponsable unidadresponsable;
     private String nombre;
     private String base;
     private int estatus;
     private Float valor;
     private Set variablechecks = new HashSet(0);

    public Variable() {
    }

	
    public Variable(int id, Unidadresponsable unidadresponsable, String nombre, int estatus) {
        this.id = id;
        this.unidadresponsable = unidadresponsable;
        this.nombre = nombre;
        this.estatus = estatus;
    }
    public Variable(int id, Unidadresponsable unidadresponsable, String nombre, String base, int estatus, Float valor, Set variablechecks) {
       this.id = id;
       this.unidadresponsable = unidadresponsable;
       this.nombre = nombre;
       this.base = base;
       this.estatus = estatus;
       this.valor = valor;
       this.variablechecks = variablechecks;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Unidadresponsable getUnidadresponsable() {
        return this.unidadresponsable;
    }
    
    public void setUnidadresponsable(Unidadresponsable unidadresponsable) {
        this.unidadresponsable = unidadresponsable;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getBase() {
        return this.base;
    }
    
    public void setBase(String base) {
        this.base = base;
    }
    public int getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(int estatus) {
        this.estatus = estatus;
    }
    public Float getValor() {
        return this.valor;
    }
    
    public void setValor(Float valor) {
        this.valor = valor;
    }
    public Set getVariablechecks() {
        return this.variablechecks;
    }
    
    public void setVariablechecks(Set variablechecks) {
        this.variablechecks = variablechecks;
    }




}


